api:
  v1_str: "/api/v1"
  project_name: "Creamoda BE"

google_oauth2:
  client_id: "752683276887-894g90indhst8745sjpeh9695uuolt9b.apps.googleusercontent.com"
  client_secret: "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"
  redirect_uri: "https://google.creamoda.ai/api/v1/auth/callback"

security:
  jwt_secret_key: "45sjpeh9695uuolt9b45sjpe45sjpeh9695uuolt9bh96945sjpeh9695uuolt9b5uuolt9b"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 10080

database:
  host: "10.26.6.189"
  port: 3306
  user: "sribd"
  password: "sribd2023#"
  name: "chimer"
  # host: "rm-2ev1h3g9294sr1vjopo.mysql.rds.aliyuncs.com"
  # port: 3306
  # user: "new_creamoda"
  # password: "new_creamoda_test2024"
  # name: "new_creamoda_test"

redis:
  host: "10.26.6.189"
  port: 6379
  password: "cspg2022"
  db: 1
  # host: "r-2evuw58o1ka6g8k5bppd.redis.rds.aliyuncs.com"
  # port: 6379
  # password: "Creamoda@2024"
  # db: 1

smtp:
  host: "smtp.feishu.cn"
  port: 465
  username: "no-reply@creamoda.ai"
  password: "WaEFPjn8uNOSiz7f"
  from_name: "creamoda" 

algorithm:
  thenewblack_email: "no-reply@chimerai.tech"
  thenewblack_password: "!W5gwscU6duZ3DE"

scheduler:
  jobstores:
    default: redis
  job_defaults:
    coalesce: true      # 堆积的任务只跑一次
    max_instances: 1    # 同一个任务同时只能有一个实例
    misfire_grace_time: 60  # 任务错过执行时间的容错范围(秒)

oss:
  access_key_id: "LTAI5tS9WAmWwjbVsuKv6YBf"
  access_key_secret: "Ur2lyCA3tXHsklbI6SwVhoReAgfmYj"
  endpoint: "https://oss-cn-beijing.aliyuncs.com"
  bucket_name: "creamoda-test"
  url_prefix: "https://creamoda-test.oss-cn-beijing.aliyuncs.com"
  upload_dir: "uploads/"