api:
  v1_str: "/api/v1"
  project_name: "Creamoda BE"

# google_oauth2:
#   client_id: "752683276887-894g90indhst8745sjpeh9695uuolt9b.apps.googleusercontent.com"
#   client_secret: "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"
#   redirect_uri: "https://test-mvp.creamoda.ai/google-callback"

google_oauth2:
  client_id: "494292609257-bpkdqdn2f817mno2vnb1pks845pdq41c.apps.googleusercontent.com"
  client_secret: "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"
  redirect_uri: "https://test-mvp.creamoda.ai/create/google-callback"


security:
  jwt_secret_key: "45sjpeh9695uuolt9b45sjpe45sjpeh9695uuolt9bh96945sjpeh9695uuolt9b5uuolt9b"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 10080

database:
  host: "rm-bp15vgy612f39t5p05o.mysql.rds.aliyuncs.com"
  port: 3306
  user: "new_creamoda"
  password: "new_creamoda_test2024"
  name: "chimer_test"

# redis:
#   host: "r-bp1ml0wy14mbtvzpkfpd.redis.rds.aliyuncs.com"
#   port: 6379
#   username: "local_test"
#   password: "chimer_test!@1"
#   db: 1


redis:
  host: "localhost"
  port: 6379
  db: 4


smtp:
  host: "smtp.feishu.cn"
  port: 465
  username: "no-reply@creamoda.ai"
  password: "DWknazFVWCoHfY7l"
  from_name: "creamoda" 

algorithm:
  thenewblack_email: "no-reply@chimerai.tech"
  thenewblack_password: "!W5gwscU6duZ3DE"
  openrouter_api_key: "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"
  infiniai_api_key: "sk-br2so27makyp242a"
  replicate_api_key: "r8_7fkn9hNYZIEh0DXvnYhx5JayXfX8BJ72PryG7"
  # ideogram_api_key: "Dmtw8y7Z3EE9faqNmjk0gd8wAQ0W25VFSMJ-rH5_j1F3UVa1dFkv8jaj21bog_b4JnHSxo9WrKAXuOfdnvgv_w"
  ideogram_api_key: "Q8gitBO69TPFK4SxuyRRdf98RFiz5X0HkCj2a7xFO9uUDaYNN4PFu1Yk6fnFWASHjdhc5XQ-a96n9f946EtReg"

scheduler:
  enabled: true
  jobstores:
    redis: redis
  job_defaults:
    coalesce: true      # 堆积的任务只跑一次
    max_instances: 1    # 同一个任务同时只能有一个实例
    misfire_grace_time: 60  # 任务错过执行时间的容错范围(秒)

oss:
  access_key_id: "LTAI5tS9WAmWwjbVsuKv6YBf"
  access_key_secret: "Ur2lyCA3tXHsklbI6SwVhoReAgfmYj"
  endpoint: "https://oss-cn-beijing.aliyuncs.com"
  bucket_name: "creamoda-test"
  url_prefix: "https://creamoda-test.oss-cn-beijing.aliyuncs.com"
  upload_dir: "uploads/"

# 添加图片生成任务配置
image_generation:
  text_to_image:
    gen_count: 1      # 文生图任务生成的图片数量
    use_credit: 1
  copy_style:
    gen_count: 1         # 洗图任务生成的图片数量
    use_credit: 1
  change_clothes: 
    gen_count: 1         # 换装任务生成的图片数量
    use_credit: 1
  fabric_to_design: 
    gen_count: 1         # 复制面料任务生成的图片数量
    use_credit: 1
  virtual_try_on: 
    gen_count: 1         # 虚拟试穿任务生成的图片数量
    use_credit: 1
  sketch_to_design:
    gen_count: 1   # 草图转设计任务生成的图片数量
    use_credit: 1
  mix_image:
    gen_count: 1          # 混合图片任务生成的图片数量
    use_credit: 1
  style_transfer:
    gen_count: 1          # 风格迁移任务生成的图片数量
    use_credit: 1
  fabric_transfer:
    gen_count: 1          # 面料转换任务生成的图片数量
    use_credit: 1
  change_color:
    gen_count: 1          # 换色任务生成的图片数量
    use_credit: 1
  change_background:
    gen_count: 1          # 换色任务生成的图片数量
    use_credit: 1
  remove_background:
    gen_count: 1          # 换色任务生成的图片数量
    use_credit: 1
  particial_modification:
    gen_count: 1          # 局部修改任务生成的图片数量
    use_credit: 1
  upscale:
    gen_count: 1          # 放大任务生成的图片数量
    use_credit: 1
  change_pattern:
    gen_count: 1          # 图案修改任务生成的图片数量
    use_credit: 1
  change_fabric:
    gen_count: 1          # 面料修改任务生成的图片数量
    use_credit: 1
  change_printing:
    gen_count: 1          # 印花修改任务生成的图片数量
    use_credit: 1
  change_pose:
    gen_count: 1          # 改变姿势任务生成的图片数量
    use_credit: 1
  style_fusion:
    gen_count: 1          # 风格融合任务生成的图片数量
    use_credit: 1
  extract_pattern:
    gen_count: 1          # 印花提取任务生成的图片数量
    use_credit: 1
  dress_printing_tryon:
    gen_count: 1          # 印花上身任务生成的图片数量
    use_credit: 1
  printing_replacement:
    gen_count: 1          # 印花替换任务生成的图片数量
    use_credit: 1
  estimated_time_seconds: 20  # 预计完成时间(秒)

paypal:
  paypal_client_id: "AZ_E6kAv80zt4_NTtcxzEUdQOG7whhjBUJVrVyWx_DtCc3osBjvpcRTKfBXV6vajFN4VvW1C-xy1Ajo-"
  paypal_secret: "EIQkwJIaJtwsjnTeNux62MGZd_N5LJMKBoiV1QoeIllpDG-cown_jzH3BX0WsXviOLdaMJGJJiw8QkMq"
  paypal_base_url: "https://api-m.sandbox.paypal.com"
  webhook_id: "3MV48135CR7843824"
  return_url: "https://test-mvp.creamoda.ai/paypal/return"
  cancel_url: "https://test-mvp.creamoda.ai/paypal/cancel"

# RabbitMQ 配置
rabbitmq:
  enabled: true
  host: "rabbitmq-cn-kf74am6dx0b.cn-hangzhou.amqp-31.net.mq.amqp.aliyuncs.com"
  port: 5672
  username: "MjpyYWJiaXRtcS1jbi1rZjc0YW02ZHgwYjpMVEFJNXRTOVdBbVd3amJWc3VLdjZZQmY="
  password: "OTI3Q0Q5OEZCRjkzOEY0NjFFNDlCNDQ2RjEwNDIyMjI1MzQxNTYyQToxNzQ5NDM2NzMyMjIw"
  virtual_host: "chimer_test"
  exchange_name: "amq.topic"
  heartbeat: 600
  blocked_connection_timeout: 300
  prefetch_count: 10
  queues:
    image_generation:
      name: "image_generation_queue"
      routing_key: "img.gen.finish"
      durable: true
      max_priority: 10

# fal.ai API 配置
fal_ai:
  api_key: "643dee3b-db85-42a9-9440-c8fee49f16ee:7dfd73425acf52b34f246dabbd8e1e3e"
  timeout: 300
